 - clean: ['~']

 - link:
     ~/.dotfiles: ''
     ~/.gitconfig: gitconfig
     ~/.vim: vim/
     ~/.vimrc: vimrc
     ~/.antigen: zsh/antigen/
     ~/.zsh: zsh/
     ~/.zshrc: zshrc
     ~/.tmux.conf: tmux.conf

 - shell:
     - git submodule update --init --recursive
     # Vim setup
     - vim +PluginInstall +qall
     # Zsh setup
     - sudo apt-get update && sudo apt-get install zsh
     - sudo chsh -s /bin/zsh
     - source .zshrc
