 - clean: ['~']

 - link:
     ~/.dotfiles: ''
     ~/.gitconfig: gitconfig
     ~/.vim: vim/
     ~/.vimrc: vimrc
     ~/.antigen: zsh/antigen/
     ~/.zsh: zsh/
     ~/.zshrc: zshrc
     ~/.tmux.conf: tmux.conf

 - shell:
     - sudo apt-get update -y && sudo apt-get upgrade -y
     - git submodule update --init --recursive
     # Vim setup
     - vim +PluginInstall +qall
     - echo "Compile YouCompleteMe if needed"
     # Zsh setup
     - echo "Make sure that you've installed zsh"
     - sudo chsh -s /bin/zsh `whoami`
     - source ~/.zshrc
